### ISSUE TITLE
1.20.2 

### ISSUE THREAD

**Issue by oblivcheck** [pog5/minecraft-freebsd#4]
I have created a [fork](https://github.com/Spokzooy/minecraft-freebsd).

New status of [#421](https://github.com/LWJGL/lwjgl3/issues/421)

The game will be able to recognize multiple CPU cores, but currently, this is limited to version 1.20.2.

**Comment by pog5** [comment]
Thank you very much, merged :D 👍🏻

**Comment by er2off** [comment]
Now lwjgl3 support is upstreamed since 3.3.4-snapshot+2. I upgraded [my port](https://github.com/er2off/freebsd-ports/tree/main/games/lwjgl3) to support it without any patches.
